name: 在 README.md 中添加贡献者头像
on:
  workflow_dispatch: # 允许手动运行action

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 生成贡献者头像
        uses: jaywcjlove/github-action-contributors@main
        id: contributors
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          openDelimiter: '<!--GAMFC_DELIMITER-->'
          closeDelimiter: '<!--GAMFC_DELIMITER-END-->'
          hideName: 'ture'
          avatarSize: 90  # 头像尺码
      
      - name: 添加 htmlTable 到 README.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          body: '${{steps.contributors.outputs.htmlTable}}'